---
- name: Instaling httpd and telnet
  hosts: all
  become: true

  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: Install telnet
      yum:
        name: telnet
        state: present

