---
- name: Install Git on Amazon Linux
  hosts: all # Replace with your instance's hostname or IP
  tasks:
    - name: Uninstall maven
      yum:
        name: maven
        state: absent
[root@ip-172-30-5-221 Ansible]# cat Script_RemoteHost.yml
- name: Transfer and execute a script.
  hosts: all
  tasks:

     - name: Copy and Execute the script 
       script: "/home/ec2-user/File.sh"
